languageCode = "en-us"
title = "Earthly Humans"
baseurl = "http://earthlyhumans.com"
theme = "earthly"
metaDataFormat = "yaml"

[permalinks]
    post = "/:slug/"
    page = "/:slug/"

[taxonomies]
    tag = "tags"
    category = "categories"

[params]
    keywords = ["humans", "philosophy", "modern", "stone age"]
    description = "A look into earthly humans all the way from Stone age to Modern day and beyond."

[[menu.header]]
    name = "Home"
    weight = 1
    url = "/"

[[menu.header]]
    name = "Resources"
    weight = 2
    url = "/resources/"

[[menu.header]]
    name = "Contact"
    weight = 3
    url = "/contact/"


[[menu.footer]]
    name = "Contact"
    weight = 1
    url = "/contact/"

[[menu.footer]]
    name = "Support Us"
    weight = 2
    url = "/support/"

